openapi: 3.1.1
info:
  title: API de Produtos
  description: Documentação da API REST de produtos
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Ambiente de Desenvolvimento
tags:
  - produtos
paths:
  /produtos:
    get:
      summary: Lista todos os produtos
      tags:
        - produtos
      responses:
        200:
          description: Lista retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
        500:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
    post:
      security:
        - token_jwt: []
      summary: Cria um produto
      tags:
        - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoCreate'
      responses:
        201:
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        400:
          description: Campos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
  /produtos/{id}:
    get:
      summary: Lista um produto pelo ID
      tags:
        - produtos
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        400:
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
    put:
      security:
        - token_jwt: []
      summary: Atualiza um produto existente
      tags:
        - produtos
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoUpdate'
      responses:
        200:
          description: Produto atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        400:
          description: ID inválido ou valor inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
    delete:
      security:
        - token_jwt: []
      summary: Deleta um produto pelo ID
      tags:
        - produtos
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        204:
          description: Produto deletado com sucesso
          content:
        400:
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        404:
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
components:
  schemas:
    Produto:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        valor:
          type: number
        esgotado:
          type: boolean
    ProdutoCreate:
      type: object
      required:
        - nome
        - valor
      properties:
        nome:
          type: string
          example: Produto Teste
        valor:
          type: number
          example: 10.5
        esgotado:
          type: boolean
          example: false
    ProdutoUpdate:
      type: object
      properties:
        nome:
          type: string
        valor:
          type: number
        esgotado:
          type: boolean
    Erro:
      type: object
      properties:
        msg:
          type: string
  securitySchemes:
    token_jwt:
      type: http
      scheme: bearer
      description: Token JWT para autenticação
